name: Docker Build Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run shell script
      run: echo commit has is ${{ github.sha }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOKER_USERNAME }}
        password: ${{ secrets.DOKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOKER_USERNAME }}/ctsemicroservices:${{ github.sha }}
    # - uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #   with:
    #     args: get namespaces
    